name: Jardins di Roma
favicon: null
layout_spectrum: 0.95778
typography_spectrum: 0.63249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b09'
    - '#bbbbbb'
    - '#474f52'
    - '#a5804b'
  brandStrength: 0.36520449351519346
  lightness: 0.7935893076937646
  saturation: 0.33167178742587566
  rhythmicContrast: 0.13898185244761407
purpose: []
